site_name: Bot

theme:
  name: material 
  favicon: assets/3d-car.png
  logo: assets/3d-car.png

  palette: 
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

nav:
  - Introduction: index.md
  - Poetry Usage Tutorial: poetry.md
