site_name: Bot-Wheels
repo_url: https://github.com/bot-wheels
repo_name: bot-wheels

theme:
  name: material 
  favicon: assets/3d-car.png
  logo: assets/3d-car.png

  palette: 
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-4 
      name: Switch to light mode
  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  
    features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer

nav:
  - Project Guide:
    - Working With Project: project_guide/working_with_project.md
    - Poetry Usage Tutorial: project_guide/poetry.md
  - Research:
    - Interface Overlay Research: research/interface_overlay_reaserch.md
    - Playing in Online Games: research/playing_in_online_games.md
    - Rocket League Bot Setup: research/rocket-league-bot-setup.md
    - Algorithms:
      - A3C: research/rl-algorithms/A3C.md
  - Biweekly Reports:
      - Week 1-2: biweekly_reports/biweekly_report_1.md

plugins:
  - search

extra:
  social:
    - icon: simple/github 
      link: https://github.com/bot-wheels

