site_name: Bot-Wheels
repo_url: https://github.com/bot-wheels
repo_name: squidfunk/bot-wheels

theme:
  name: material 
  favicon: assets/3d-car.png
  logo: assets/3d-car.png

  palette: 
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-4 
      name: Switch to light mode
  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  
    features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer

nav:
  - Introduction: index.md
  - Poetry Usage Tutorial: poetry.md

plugins:
  - search
  - social

extra:
  social:
    - icon: simple/github 
      link: https://github.com/bot-wheels

