site_name: Bot-Wheels
repo_url: https://github.com/bot-wheels
repo_name: bot-wheels

theme:
  name: material 
  favicon: assets/3d-car.png
  logo: assets/3d-car.png

  palette: 
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-4 
      name: Switch to light mode
  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  
    features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer

nav:
  - Project Guide:
    - Working With Project: project-guide/working-with-project.md
    - Poetry Usage Tutorial: project-guide/poetry.md
    - Codebase Standardization Guidelines: project-guide/codebase-standardization-guidelines.md
    - Rocket Learn Setup: project-guide/rocket-learn-setup/rocket-learn-setup.md
    - Rl-Gym-PPO Setup: project-guide/rlgym_ppo.md
  - Research:
    - Interface Overlay Research: research/interface-overlay-research.md
    - Playing in Online Games: research/playing-in-online-games.md
    - Rocket League Bot Setup: research/rocket-league-bot-setup.md
    - Implement Movement Testing Script for Bot Actions: research/implement-movement-testing-script-for-bot-actions.md
    - Match Against AI Bots: research/match-against-ai-bots.md
    - Research and Documentation of Algorithm Categories for Rocket League Bot: research/research-and-documentation-of-algorithm-categories-for-rocket-league-bot.md
    - RL algorithms:
      - A3C: research/rl-algorithms/A3C.md
      - Model based algorithms for RL bots alphazero: research/rl-algorithms/model-based-algorithms-for-rocket-league-bots-alphazero.md
      - Police Optimization Documentation from the summer: research/rl-algorithms/police-optimization-documentation-summer.md
  - Biweekly Reports:
    - Week 1-2: biweekly-reports/weekly-report-1.md
    - Week 3-4: biweekly-reports/weekly-report-2.md
    - Week 5-6: biweekly-reports/weekly-report-3.md

plugins:
  - search

extra:
  social:
    - icon: simple/github 
      link: https://github.com/bot-wheels

