name: Checks
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Proof HTML
        uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./

      - name: Install markdownlint
        run: |
          npm install -g markdownlint-cli

      - name: Run markdownlint
        run: |
          markdownlint '**/*.md' -c markdownlint.json
